/**
 * Legal document formatting utilities.
 *
 * For MVP this generates well-structured Markdown documents. In production
 * this could be extended to output PDF via pdfkit or puppeteer.
 */

export interface LegalDocumentParams {
  title: string;
  type: 'contract' | 'nda' | 'agreement' | 'other';
  parties: string[];
  body: string;
  date?: string;
}

const TYPE_LABELS: Record<LegalDocumentParams['type'], string> = {
  contract: 'CONTRACT',
  nda: 'NON-DISCLOSURE AGREEMENT',
  agreement: 'AGREEMENT',
  other: 'LEGAL DOCUMENT',
};

/**
 * Generate a formatted legal document in Markdown.
 *
 * The output is a self-contained Markdown string suitable for preview
 * in the chat UI and storage as an approval task payload.
 *
 * TODO: In production, convert to PDF using pdfkit or puppeteer for
 * downloadable / printable versions.
 */
export function generateLegalDocument(params: LegalDocumentParams): string {
  const {
    title,
    type,
    parties,
    body,
    date = new Date().toISOString().split('T')[0],
  } = params;

  const typeLabel = TYPE_LABELS[type];

  const partiesSection = parties
    .map((party, idx) => `${idx + 1}. **${party}** (hereinafter referred to as "Party ${idx + 1}")`)
    .join('\n');

  return `# ${typeLabel}

## ${title}

**Date:** ${date}

---

### Parties

${partiesSection}

---

### Terms and Conditions

${body}

---

### Signatures

${parties.map((party, idx) => `**Party ${idx + 1} (${party}):**\n\n_________________________\nSignature / Date\n`).join('\n')}

---

*This document was generated by the AgentTeam Lawyer agent and requires human review and approval before it becomes legally binding.*
`;
}
